<?php
/** @var \Wedding\Enquiry $enquiry */
$enquiry = $this->enquiry;
$groups = $this->itemGroups;

$days = \Wedding\Source\Day::getOptions();
$months = \Wedding\Source\Month::getOptions();
$excs = \Wedding\Source\ExclusiveUse::getOptions();


$quoteData = [];
if($this->new !== true) {
    /** @var \Wedding\Quote $quote */
    $quote = $this->quote;
    $quoteData = $quote->toArray();
}

?>
<div class="col-md-12">
    <form method="post" action="<?php echo \Wedding::getUrl('quote/editPost');?>" class="form-horizontal">

        <div class="no-display">
            <input type="hidden" name="quote[enquiry_id]" value="<?php echo $enquiry->getEntityId();?>" />
        </div>

        <div class="panel panel-default">
            <div class="panel-heading">Create Quote</div>
            <div class="panel-body">

                <div class="col-md-6">
                    <div class="form-group">
                        <div class="col-sm-2"><strong>Quote No#</strong></div>
                        <div class="col-sm-10">
                            <?php echo $this->new ? 'New Quote' : 'ID';?>

                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-2"><strong>Names</strong></div>
                        <div class="col-sm-10"><?php echo $enquiry->getCouple();?></div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-2"><strong>Viewing Date</strong></div>
                        <div class="col-sm-10">

                        </div>
                    </div>

                </div>

                <div class="col-md-6">
                    <div class="form-group">
                        <div class="col-sm-2"><strong>Email</strong></div>
                        <div class="col-sm-10"><?php echo $enquiry->getEmail();?></div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-2"><strong>Phone</strong></div>
                        <div class="col-sm-10"><?php echo $enquiry->getPhoneNumbers();?></div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-2"><strong>Address</strong></div>
                        <div class="col-sm-10"><?php echo $enquiry->getAddress();?></div>
                    </div>
                </div>

            </div>
        </div>


        <div class="panel panel-default">
            <div class="panel-heading">Wedding Details</div>
            <div class="panel-body">

                <div class="row">
                    <div class="col-md-6">

                        <div class="form-group">
                            <label class="col-sm-2 control-label">Day of Week</label>
                            <div class="col-sm-10">
                                <?php foreach($days as $day) : ?>
                                    <label class="checkbox-inline">
                                        <input
                                            <?php echo isset($quoteData['Day']) && in_array($day, explode(',', $quoteData['Day'])) ? 'checked="checked"' : '';?>
                                            type="checkbox"
                                            value="1"
                                            name="quote[day][<?php echo $day;?>]"> <?php echo \Wedding::__($day); ?>
                                    </label>
                                <?php endforeach;?>
                            </div>
                        </div>


                        <div class="form-group">
                            <label class="col-sm-2 control-label">Month</label>
                            <div class="col-sm-10">
                                <?php foreach($months as $month) : ?>
                                    <label class="checkbox-inline">
                                        <input
                                            <?php echo isset($quoteData['Month']) && in_array($month, explode(',', $quoteData['Month'])) ? 'checked="checked"' : '';?>
                                            type="checkbox"
                                            value="1"
                                            name="quote[month][<?php echo $month;?>]"> <?php echo \Wedding::__($month); ?>
                                    </label>

                                    <?php if ($month == 'Jun') {
                                        echo '<br clear="all" />';
                                    }
                                    ?>
                                <?php endforeach;?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="year">Year</label>
                            <div class="col-sm-10">
                                <select name="quote[year]" class="form-control">
                                    <?php echo \Wedding\Source\Year::getOptionHtml(isset($quoteData['Year']) ? $quoteData['Year'] : '');?>
                                </select>
                            </div>
                        </div>
                    </div>


                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="col-sm-2 control-label">Exclusive Use</label>
                            <div class="col-sm-10">
                                <?php foreach($excs as $exc) : ?>
                                    <label class="checkbox-inline">
                                        <input
                                                <?php echo isset($quoteData['Exclusive']) && in_array($exc, explode(',', $quoteData['Exclusive'])) ? 'checked="checked"' : '';?>
                                                type="checkbox"
                                                value="1"
                                                name="quote[exc][<?php echo $exc;?>]"> <?php echo \Wedding::__($exc); ?>
                                    </label>

                                <?php endforeach;?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="date">Specific Date</label>
                            <div class="col-sm-10">
                                <input id="date" type="text" name="quote[date]" class="form-control" value="<?php echo isset($quoteData['SpecificDate']) ? $quoteData['SpecificDate'] : '';?>"/>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="dayg">Day Guests</label>
                            <div class="col-sm-10">
                                <input id="dayg" type="text" name="quote[dayg]" class="form-control" value="<?php echo isset($quoteData['DayGuests']) ? $quoteData['DayGuests'] : '';?>"/>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="eveg">Eve Guests</label>
                            <div class="col-sm-10">
                                <input id="eveg" type="text" name="quote[eveg]" class="form-control" value="<?php echo isset($quoteData['EveGuests']) ? $quoteData['EveGuests'] : '';?>" />
                            </div>
                        </div>


                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="year">Ceremony Type</label>
                            <div class="col-sm-10">
                                <select name="quote[ceremony]" class="form-control">
                                    <?php echo \Wedding\Source\Ceremony::getOptionHtml();?>
                                </select>
                            </div>
                        </div>
                    </div>

                </div>

                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="notes">Notes</label>
                            <div class="col-sm-10">
                                <textarea id="notes" type="text" name="quote[notes]" class="form-control"><?php
                                    echo isset($quoteData['Notes']) ? $quoteData['Notes'] : ''
                                ?></textarea>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>



        <div class="panel panel-default">
            <div class="panel-heading">Details</div>
            <div class="panel-body">
                    <?php
                /** @var \Wedding\QuoteItemGroup $group */
                foreach($groups as $i => $group) :
                    ?>
                    <div class="row">
                        <div class="col-md-12">
                            <h3><?php echo $group->getName();?></h3>

                            <div class="js-items-wrap">
                                <?php $ptr = 0; ?>


                                <?php foreach($quote->getQuoteItems() as $quoteItem) : ?>
                                    <?php if($quoteItem->getQuoteItemGroupItemId() == $group->getEntityId()) : ?>
                                        <?php echo $this->partial('quote/partial/item.phtml', [
                                            'group' => $group,
                                            'item' => $quoteItem,
                                            'ptr' => $ptr
                                        ]); ?>

                                        <?php $ptr++; ?>
                                    <?php endif; ?>
                                <?php endforeach; ?>


                                <?php if($ptr == 0) : ?>
                                    <?php echo $this->partial('quote/partial/item.phtml', [
                                        'group' => $group,
                                        'ptr' => $ptr,
                                        'new' => true
                                    ]); ?>
                                <?php endif; ?>

                                <?php
                                /*
                                ?>
                                <div class="row js-item">
                                    <div class="col-md-3">
                                        <select name="quote[item_group][<?php echo $group->getEntityId();?>][0][item]" class="form-control js-cloneable">
                                            <option value="0">Please select...</option>
                                            <?php foreach($group->getQuoteItemGroupItems() as $item) : ?>
                                                <option data-price="<?php echo $item->getSuggestedPrice();?>" value="<?php echo $item->getEntityId();?>"><?php echo $item->getOptionString();?></option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>

                                    <div class="col-md-1">
                                        <input name="quote[item_group][<?php echo $group->getEntityId();?>][0][qty]" class="form-control js-cloneable" type="number" placeholder="qty" />
                                    </div>

                                    <div class="col-md-5">
                                        <input  name="quote[item_group][<?php echo $group->getEntityId();?>][0][notes]" class="form-control js-cloneable" type="text" placeholder="Enter any notes regarding this item" />
                                    </div>

                                    <div class="col-md-1">
                                        <input  name="quote[item_group][<?php echo $group->getEntityId();?>][0][price]" class="form-control js-cloneable" type="text" placeholder="Price" />
                                    </div>

                                    <div class="col-md-2">
                                        <button type="button" class="btn btn-primary btn-xs js-add-row"><span class="glyphicon glyphicon-plus-sign"></span> Add</button>
                                        <button type="button" class="btn btn-danger btn-xs js-del-row"><span class="glyphicon glyphicon-trash"></span> Remove</button>
                                    </div>
                                </div>
                                */
                                ?>


                            </div>
                        </div>

                    </div>
                <?php endforeach; ?>
            </div>
        </div>

        <div class="row">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>
</div>