<?php
/** @var \Wedding\Enquiry $enquiry */
$enquiry = $this->enquiry;
$groups = $this->itemGroups;

$days = \Wedding\Source\Day::getOptions();
$months = \Wedding\Source\Month::getOptions();
$excs = \Wedding\Source\ExclusiveUse::getOptions();

?>
<div class="col-md-12">
    <form method="post" action="<?php echo \Wedding::getUrl('quote/editPost');?>" class="form-horizontal">

        <div class="no-display">

        </div>

        <div class="panel panel-default">
            <div class="panel-heading">Create Quote</div>
            <div class="panel-body">

                <div class="col-md-6">
                    <div class="form-group">
                        <div class="col-sm-2"><strong>Quote No#</strong></div>
                        <div class="col-sm-10">
                            <?php echo $this->new ? 'New Quote' : 'ID';?>

                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-2"><strong>Names</strong></div>
                        <div class="col-sm-10"><?php echo $enquiry->getCouple();?></div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-2"><strong>Viewing Date</strong></div>
                        <div class="col-sm-10">

                        </div>
                    </div>

                </div>

                <div class="col-md-6">
                    <div class="form-group">
                        <div class="col-sm-2"><strong>Email</strong></div>
                        <div class="col-sm-10"><?php echo $enquiry->getEmail();?></div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-2"><strong>Phone</strong></div>
                        <div class="col-sm-10"><?php echo $enquiry->getPhoneNumbers();?></div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-2"><strong>Address</strong></div>
                        <div class="col-sm-10"><?php echo $enquiry->getAddress();?></div>
                    </div>
                </div>

            </div>
        </div>


        <div class="panel panel-default">
            <div class="panel-heading">Wedding Details</div>
            <div class="panel-body">

                <div class="row">
                    <div class="col-md-6">

                        <div class="form-group">
                            <label class="col-sm-2 control-label">Day of Week</label>
                            <div class="col-sm-10">
                                <?php foreach($days as $day) : ?>
                                    <label class="checkbox-inline">
                                        <input type="checkbox" value="1" name="quote[day][<?php echo $day;?>]"> <?php echo \Wedding::__($day); ?>
                                    </label>
                                <?php endforeach;?>
                            </div>
                        </div>


                        <div class="form-group">
                            <label class="col-sm-2 control-label">Month</label>
                            <div class="col-sm-10">
                                <?php foreach($months as $month) : ?>
                                    <label class="checkbox-inline">
                                        <input type="checkbox" value="1" name="quote[month][<?php echo $day;?>]"> <?php echo \Wedding::__($month); ?>
                                    </label>

                                    <?php if ($month == 'Jun') {
                                        echo '<br clear="all" />';
                                    }
                                    ?>
                                <?php endforeach;?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="year">Year</label>
                            <div class="col-sm-10">
                                <select name="quote[year]" class="form-control">
                                    <?php echo \Wedding\Source\Year::getOptionHtml();?>
                                </select>
                            </div>
                        </div>
                    </div>


                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="col-sm-2 control-label">Exclusive Use</label>
                            <div class="col-sm-10">
                                <?php foreach($excs as $exc) : ?>
                                    <label class="checkbox-inline">
                                        <input type="checkbox" value="1" name="quote[exc][<?php echo $exc;?>]"> <?php echo \Wedding::__($exc); ?>
                                    </label>

                                <?php endforeach;?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="date">Specific Date</label>
                            <div class="col-sm-10">
                                <input id="date" type="text" name="quote[date]" class="form-control" />
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="dayg">Day Guests</label>
                            <div class="col-sm-10">
                                <input id="dayg" type="text" name="quote[dayg]" class="form-control" />
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="eveg">Eve Guests</label>
                            <div class="col-sm-10">
                                <input id="eveg" type="text" name="quote[eveg]" class="form-control" />
                            </div>
                        </div>


                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="year">Ceremony Type</label>
                            <div class="col-sm-10">
                                <select name="quote[ceremony]" class="form-control">
                                    <?php echo \Wedding\Source\Ceremony::getOptionHtml();?>
                                </select>
                            </div>
                        </div>
                    </div>

                </div>

                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="notes">Notes</label>
                            <div class="col-sm-10">
                                <textarea id="notes" type="text" name="quote[notes]" class="form-control"></textarea>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>



        <div class="panel panel-default">
            <div class="panel-heading">Details</div>
            <div class="panel-body">
                    <?php
                /** @var \Wedding\QuoteItemGroup $group */
                foreach($groups as $group) :
                    ?>
                    <div class="row">
                        <div class="col-md-12">
                            <h3><?php echo $group->getName();?></h3>

                            <div class="row">
                                <div class="col-md-3">
                                    <select class="form-control">
                                        <option>Please select...</option>
                                        <?php foreach($group->getQuoteItemGroupItems() as $item) : ?>
                                            <option value="<?php echo $item->getEntityId();?>"><?php echo $item->getOptionString();?></option>
                                        <?php endforeach; ?>
                                    </select>
                                </div>

                                <div class="col-md-1">
                                    <input class="form-control" type="number" placeholder="qty" />
                                </div>

                                <div class="col-md-5">
                                    <input class="form-control" type="text" placeholder="Enter any notes regarding this item" />
                                </div>

                                <div class="col-md-1">
                                    <input class="form-control" type="text" placeholder="Price" />
                                </div>

                                <div class="col-md-2">
                                    btns
                                </div>
                            </div>
                        </div>

                    </div>
                <?php endforeach; ?>
            </div>
        </div>

        <div class="row">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>





    </form>


</div>