<!-- Modal -->
<div class="modal fade" id="viewingModal" tabindex="-1" role="dialog" aria-labelledby="viewingLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title h3" id="viewingLabel">Mark as Done</h4>
            </div>
            <div class="modal-body">
                <div class="enquiry-information">
                    <div class="row">
                        <div class="col-md-2">Couple</div>
                        <div class="col-md-10 js-viewing-couple"></div>
                    </div>

                    <div class="row">
                        <div class="col-md-2">Contact</div>
                        <div class="col-md-10 js-viewing-email"></div>
                    </div>

                    <div class="row">
                        <div class="col-md-2">Created At</div>
                        <div class="col-md-10 js-viewing-created-at"></div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Mark as Done</button>
            </div>
        </div>
    </div>
</div>