<?php $collection = $this->collection; ?>
<div class="col-md-2">
    <div class="list-group" style="margin-top:40px;">
        <h4>Quote Items</h4>
        <!-- add active class -->
        <a href="#" class="list-group-item">Groups</a>
        <a href="#" class="list-group-item">Group Items</a>
    </div>
</div>
<div class="col-md-offset-1 col-md-9 main">

    <div class="row">
        <h1 class="page-header">Admin Area</h1>

    </div>
</div>