<?php
/** @var \Wedding\Enquiry $enq */
$enq = $this->enquiry;?>

<?php $commentHistory = \Wedding\EnquiryComment::getHistory($enq->getEntityId());?>

<div class="table-responsive comment-history">
    <table class="table table-striped">
        <colgroup>
            <col width="140">
            <col width="70">
            <col width="100">
            <col />
        </colgroup>
        <thead>
        <tr>
            <th>Date</th>
            <th>Time</th>
            <th>Type</th>
            <th>Comment</th>
        </tr>
        </thead>
        <tbody class="list">
        <?php
        /** @var \Wedding\EnquiryComment $comment */
        foreach($commentHistory as $comment) : ?>
            <tr>
                <td><?php echo $comment->getCreatedAt()->format('D d/m/Y');?></td>
                <td><?php echo $comment->getCreatedAt()->format('H:i');?></td>
                <td><?php echo $comment->getStaffId() == null ? 'AUTO' : 'TBC';?></td>
                <td><?php echo \Wedding::__($comment->getComment());?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>