<?php $collection = $this->collection; ?>
<div class="col-md-12 main">

    <div class="row">
        <h1 class="page-header">Quotes</h1>


        <div id="lead-srt">

            <div class="row">
                <div class="col-md-11">
                    <div class="form-group">
                        <label for="name" class="hidden">Name</label>
                        <input class="search form-control" placeholder="Search Quotes..." />
                    </div>

                </div>
                <div class="col-md-1">
                    <a href="<?php echo \Wedding::getUrl('quote/add');?>" class="btn btn-primary pull-right">Add New</a>
                </div>
            </div>

            <div class="table-responsive">
                <table class="table table-striped">
                    <colgroup>
                        <col width="200">
                        <col />
                        <col width="100">
                        <col width="100">
                        <col width="100">
                        <col width="300">
                    </colgroup>
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Date</th>
                        <th>Value</th>
                        <th>Names</th>
                        <th>Contacts</th>
                        <th class="text-right">Actions</th>
                    </tr>
                    </thead>
                    <tbody class="list">
                    <?php
                    /** @var \Wedding\Quote $quote */
                    foreach($collection as $quote) : ?>
                        <tr class="<?php //echo $quote->getStatusClass();?>">
                            <td class="srt-num num"><?php echo \Wedding::__($quote->getEntityId());?></td>
                            <td class="srt-date date"><?php echo \Wedding::__($quote->getCreatedAt()->format('d/m/Y'));?></td>
                            <td class="srt-value value"><?php echo \Wedding::currency($quote->getValue());?></td>
                            <td class="srt-name name"><?php echo \Wedding::__($quote->getEnquiry()->getCouple());?></td>
                            <td class="contacts">tbc</td>
                            <td class="text-right">
                                <a title="Edit Item" class="btn-sm btn-default js-entry-edit" href="<?php echo \Wedding::getUrl('quote/edit', ['enquiry_id' => $quote->getEnquiryId(), 'quote_id' => $quote->getEntityId()]);?>"><span class="glyphicon glyphicon-pencil"></span><span class="hidden">Edit</span></a>
                            </td>
                        </tr>
                    <?php endforeach;?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>